### PR TITLE
Begin of refactor

### PR DESCRIPTION
**Pull request by ImperatorS79**
I have splitted the big structure into smaller ones:
- Mesh2D: 
    - Entity2D:
        - Element2D:
            - Edge

The rest is basically rewriting readMesh to deal with that structure format.
This is unfinished as you can see.

NB: since basisFunctionTypeGrad is "Grad" + basisFunctionType, I think it is safer to delete that variable and do the concatenation in code, what do you think ?

### CODE REVIEW

**Comment by ImperatorS79** [comment]
@tgregov False maneuver ? :stuck_out_tongue:

**Comment by tgregov** [comment]
Yes ahahah The commits in the new branch were not that important (only delete unused stuff + put comments in .hpp)

**Comment by ImperatorS79** [comment]
Do you want me to create the PR against master ?

**Comment by tgregov** [comment]
Maybe we could just create a new branch with your last commits ?

**Comment by ImperatorS79** [comment]
I will create the branch and make the PR against it then ;-).

@tgregov I do not know how but my commits ended up inside master :thinking: .

**Comment by tgregov** [comment]
hmm should we continue in master then ?

**Comment by ImperatorS79** [comment]
I would have prefer to have it inside a PR to review it before merging.
I don't know if we can revert the last commit (but I'm nearly sure it is possible somehow).

**Comment by tgregov** [comment]
Ok, I let you do that, since you're better at Github than me 😄

**Pull request closed without merging**
